export type TileSize = "1x1" | "2x1" | "1x2" | "2x2" | "3x2";

export type Tile =
  | {
      kind: "image";
      src: string;
      alt: string;
      size: TileSize;
      rate: number; // parallax rate (0.0 = static, 0.08 = lively)
      kb?: [number, number]; // Ken Burns: transform-origin in %, zoom toward this point
      objectPosition?: string; // CSS object-position — e.g. "bottom", "50% 100%"
    }
  | {
      kind: "card";
      emoji: string;
      text: string;
      tone: "terracotta" | "mint" | "mustard" | "rose" | "navy";
      size: TileSize;
      rate: number;
    };

// Paths are URL-encoded to handle the space in "portfolio transfer"
const PT = "/portfolio%20transfer";

export const TILES: Tile[] = [
  // ── Hero wapo + kin ────────────────────────────────────────────────
  {
    kind: "image",
    src: `${PT}/washington-post-homepage.gif`,
    alt: "Washington Post homepage redesign",
    size: "2x2",
    rate: 0,
    kb: [22, 22],
  },
  {
    kind: "image",
    src: `${PT}/Europalette/IMG_0390.jpeg`,
    alt: "Europe",
    size: "2x1",
    rate: 0.05,
  },
  {
    kind: "card",
    emoji: "🎻",
    text: "Violin for 30 years.",
    tone: "mustard",
    size: "1x2",
    rate: 0,
  },
  {
    kind: "image",
    src: `${PT}/me/IMG_0077.jpeg`,
    alt: "Peter",
    size: "1x1",
    rate: 0.07,
  },
  {
    kind: "card",
    emoji: "🌍",
    text: "Approaching 50 countries.",
    tone: "rose",
    size: "1x1",
    rate: 0,
  },
  {
    kind: "image",
    src: `${PT}/cooking.gif`,
    alt: "Cooking",
    size: "1x1",
    rate: 0.06,
  },
  {
    kind: "image",
    src: `${PT}/HKfilm/hongkong-slideshow_0000_Layer-3.png`,
    alt: "Hong Kong on 35mm film",
    size: "3x2",
    rate: 0.04,
  },
  {
    kind: "card",
    emoji: "📝",
    text: "Weekly cartoon at 15.",
    tone: "terracotta",
    size: "1x1",
    rate: 0,
  },
  {
    kind: "image",
    src: `${PT}/Europalette/IMG_0735.jpeg`,
    alt: "Europe",
    size: "1x2",
    rate: 0.04,
  },
  {
    kind: "image",
    src: `${PT}/HKfilm/hongkong-slideshow_0000_Layer-6.png`,
    alt: "Hong Kong on 35mm film",
    size: "2x1",
    rate: 0.05,
  },
  {
    kind: "image",
    src: `${PT}/me/IMG_7593.jpeg`,
    alt: "Peter",
    size: "1x2",
    rate: 0.06,
  },
  {
    kind: "image",
    src: `${PT}/Europalette/IMG_1160.jpeg`,
    alt: "Europe",
    size: "1x1",
    rate: 0.07,
  },
  {
    kind: "image",
    src: `${PT}/Europalette/IMG_0839.jpeg`,
    alt: "Europe",
    size: "3x2",
    rate: 0.04,
  },

  // ── beingbecoming + kin ────────────────────────────────────────────
  {
    kind: "image",
    src: `${PT}/beingbecoming.gif`,
    alt: "Being / Becoming — generative piece",
    size: "2x2",
    rate: 0,
    kb: [78, 22],
  },
  {
    kind: "image",
    src: `${PT}/me/IMG_1630.jpeg`,
    alt: "Peter",
    size: "1x1",
    rate: 0.08,
  },
  {
    kind: "image",
    src: `${PT}/screen_context.gif`,
    alt: "Screen context demo",
    size: "2x1",
    rate: 0.04,
    objectPosition: "center bottom",
  },
  {
    kind: "image",
    src: `${PT}/HKfilm/hongkong-slideshow_0002_Layer-1.png`,
    alt: "Hong Kong on 35mm film",
    size: "1x1",
    rate: 0.07,
  },
  {
    kind: "card",
    emoji: "🎬",
    text: "Former child actor.",
    tone: "mint",
    size: "1x1",
    rate: 0,
  },
  {
    kind: "image",
    src: `${PT}/sculpture2.0.mp4`,
    alt: "Sculpture",
    size: "2x1",
    rate: 0.04,
  },
  {
    kind: "card",
    emoji: "🗣️",
    text: "Shaped Veo video gen.",
    tone: "navy",
    size: "1x1",
    rate: 0,
  },
  {
    kind: "image",
    src: `${PT}/me/IMG_3476.JPG`,
    alt: "Peter",
    size: "1x2",
    rate: 0.06,
  },
  {
    kind: "image",
    src: `${PT}/Europalette/IMG_9026.jpeg`,
    alt: "Europe",
    size: "2x1",
    rate: 0.05,
  },
  {
    kind: "image",
    src: `${PT}/HKfilm/hongkong-slideshow_0001_Layer-5.png`,
    alt: "Hong Kong on 35mm film",
    size: "1x2",
    rate: 0.05,
  },

  // ── Papercut + variety ─────────────────────────────────────────────
  {
    kind: "image",
    src: `${PT}/papercut.gif`,
    alt: "Papercut",
    size: "2x2",
    rate: 0,
    kb: [22, 78],
  },
  {
    kind: "image",
    src: `${PT}/Europalette/IMG_0513.jpeg`,
    alt: "Europe",
    size: "1x1",
    rate: 0.08,
  },
  {
    kind: "card",
    emoji: "🇲🇲",
    text: "Produced a doc series in Myanmar.",
    tone: "rose",
    size: "2x1",
    rate: 0,
  },
  {
    kind: "image",
    src: `${PT}/me/IMG_1917.jpeg`,
    alt: "Peter",
    size: "1x1",
    rate: 0.06,
  },
  {
    kind: "card",
    emoji: "🏛️",
    text: "Built digital experiences for the feds.",
    tone: "terracotta",
    size: "2x1",
    rate: 0,
  },
  {
    kind: "image",
    src: `${PT}/gemini_visualoverlays_commercial_2.gif`,
    alt: "Gemini visual overlays commercial",
    size: "3x2",
    rate: 0.03,
  },
  {
    kind: "image",
    src: `${PT}/HKfilm/hongkong-slideshow_0006_PH_464_P400_008941-R1-071-34.png`,
    alt: "Hong Kong on 35mm film",
    size: "3x2",
    rate: 0.04,
  },
  {
    kind: "card",
    emoji: "📰",
    text: "Redesigned the WaPo homepage.",
    tone: "navy",
    size: "1x1",
    rate: 0,
  },
  {
    kind: "image",
    src: `${PT}/gemini-app-ios-1.webp`,
    alt: "Gemini app on iOS",
    size: "1x2",
    rate: 0.04,
  },
  {
    kind: "image",
    src: `${PT}/gemini_vss_commercial_lindsaylohan.gif`,
    alt: "Gemini VSS commercial — Lindsay Lohan",
    size: "1x2",
    rate: 0.04,
  },
  {
    kind: "image",
    src: `${PT}/voice_selection.gif`,
    alt: "Assistant voice selection",
    size: "1x1",
    rate: 0.05,
  },
  {
    kind: "image",
    src: `${PT}/Europalette/IMG_9325.jpeg`,
    alt: "Europe",
    size: "2x1",
    rate: 0.05,
  },
  {
    kind: "image",
    src: `${PT}/me/IMG_4841.JPG`,
    alt: "Peter",
    size: "1x2",
    rate: 0.06,
  },
  {
    kind: "image",
    src: `${PT}/Europalette/IMG_1613.jpeg`,
    alt: "Europe",
    size: "2x1",
    rate: 0.05,
  },
  {
    kind: "image",
    src: `${PT}/2D22465D-A2E1-4847-9AE5-144DF669B8C0.jpg`,
    alt: "A photograph",
    size: "1x1",
    rate: 0.06,
  },

  // ── TNP + tail ─────────────────────────────────────────────────────
  {
    kind: "image",
    src: `${PT}/TNP.gif`,
    alt: "The Noted Project",
    size: "2x2",
    rate: 0,
    kb: [78, 78],
  },
  {
    kind: "image",
    src: `${PT}/IMG_9296.jpeg`,
    alt: "A photograph",
    size: "1x1",
    rate: 0.07,
  },
  {
    kind: "image",
    src: `${PT}/gemini_VSS_samsung.gif`,
    alt: "Gemini VSS commercial — Samsung",
    size: "2x2",
    rate: 0.02,
  },
  {
    kind: "image",
    src: `${PT}/Europalette/IMG_0145.jpeg`,
    alt: "Europe",
    size: "1x1",
    rate: 0.04,
  },
  {
    kind: "card",
    emoji: "🇨🇴",
    text: "Freelanced across South America.",
    tone: "mustard",
    size: "1x1",
    rate: 0,
  },
  {
    kind: "card",
    emoji: "🥖",
    text: "Sourdough most weekends.",
    tone: "mustard",
    size: "1x1",
    rate: 0,
  },
  {
    kind: "card",
    emoji: "🧾",
    text: "2 patents at Google.",
    tone: "mint",
    size: "1x1",
    rate: 0,
  },
  {
    kind: "image",
    src: `${PT}/HKfilm/hongkong-slideshow_0001_Layer-2.png`,
    alt: "Hong Kong on 35mm film",
    size: "1x1",
    rate: 0.06,
  },
  {
    kind: "card",
    emoji: "✨",
    text: "Pitched the Gemini apps.",
    tone: "terracotta",
    size: "1x1",
    rate: 0,
  },
  {
    kind: "image",
    src: `${PT}/IMG_0822.MOV`,
    alt: "Video clip",
    size: "2x1",
    rate: 0.05,
  },
  {
    kind: "card",
    emoji: "💃",
    text: "Shot an improvised dance film.",
    tone: "mint",
    size: "1x1",
    rate: 0,
  },
  {
    kind: "image",
    src: `${PT}/me/IMG_7918.jpeg`,
    alt: "Peter",
    size: "1x2",
    rate: 0.06,
  },
  {
    kind: "image",
    src: `${PT}/HKfilm/hongkong-slideshow_0005_000005080003.png`,
    alt: "Hong Kong on 35mm film",
    size: "2x1",
    rate: 0.05,
  },
  {
    kind: "image",
    src: `${PT}/me/IMG_7950.JPG`,
    alt: "Peter",
    size: "1x1",
    rate: 0.08,
  },
  {
    kind: "image",
    src: `${PT}/Europalette/IMG_9036.jpeg`,
    alt: "Europe",
    size: "1x2",
    rate: 0.05,
  },
  {
    kind: "image",
    src: `${PT}/HKfilm/hongkong-slideshow_0007_000005080013.png`,
    alt: "Hong Kong on 35mm film",
    size: "1x1",
    rate: 0.07,
  },
  {
    kind: "image",
    src: `${PT}/Europalette/IMG_2480.jpeg`,
    alt: "Europe",
    size: "2x1",
    rate: 0.04,
  },
  {
    kind: "image",
    src: `${PT}/me/IMG_6646.jpeg`,
    alt: "Peter",
    size: "1x1",
    rate: 0.06,
  },
  {
    kind: "image",
    src: `${PT}/HKfilm/hongkong-slideshow_0007_PH_464_P400_008941-R1-053-25.png`,
    alt: "Hong Kong on 35mm film",
    size: "1x2",
    rate: 0.05,
  },
  {
    kind: "image",
    src: `${PT}/me/IMG_1959.jpeg`,
    alt: "Peter",
    size: "1x2",
    rate: 0.06,
  },
  {
    kind: "image",
    src: `${PT}/IMG_2083.JPG`,
    alt: "A photograph",
    size: "1x1",
    rate: 0.06,
  },
  {
    kind: "image",
    src: `${PT}/Europalette/IMG_9051.jpeg`,
    alt: "Europe",
    size: "2x1",
    rate: 0.04,
  },
  {
    kind: "image",
    src: `${PT}/me/IMG_8141.jpeg`,
    alt: "Peter",
    size: "1x1",
    rate: 0.07,
  },
  {
    kind: "image",
    src: `${PT}/Europalette/IMG_9269.jpeg`,
    alt: "Europe",
    size: "1x2",
    rate: 0.05,
  },
  {
    kind: "image",
    src: `${PT}/Europalette/IMG_1709.jpeg`,
    alt: "Europe",
    size: "1x1",
    rate: 0.06,
  },
  {
    kind: "image",
    src: `${PT}/Europalette/IMG_2064.jpeg`,
    alt: "Europe",
    size: "2x1",
    rate: 0.05,
  },
  {
    kind: "image",
    src: `${PT}/Europalette/IMG_9680.jpeg`,
    alt: "Europe",
    size: "1x2",
    rate: 0.05,
  },
];
